name: Linting
on:
  pull_request:

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Test with pytest
      run: |
        python .github/vyos-linter.py
