name: Update submodule vyos-1x
on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '*/15 * * * *'
jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: rebortg/vyos-documentation
      - name: update submodule
        run: |
          git submodule status
          cd docs/_include/vyos-1x
          git checkout current
          git pull
          git submodule status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          commit-message: Update vyos-1x submodule
          title: Update vyos-1x submodule
          branch: update-dependencies
