name: Update submodule vyos-1x
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
  #schedule:
  #  - cron:  '*/15 * * * *'
jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: vyos/vyos-documentation
      - name: update submodule
        run: |
          cd docs/_include/vyos-1x
          git pull
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch: submodul-update
