name: Update submodule vyos-1x
on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '*/15 * * * *'
jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: rebortg/vyos-documentation
      - name: update submodule
        run: |
          git submodule foreach git pull
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          branch: submodul-update
